project:
  type: website
  output-dir: docs

website:
  title: "Nitish's Website"
  navbar:
    background: dark
    search: true
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
  page-footer: 
    left: "Copyright 2022, Nitish Raj"
    right:
      - icon: github
        href: https://github.com/nitish-raj/nitish-raj.github.io
    background: light
  reader-mode: true
  repo-url: https://github.com/nitish-raj/nitish-raj.github.io
  repo-actions: [edit, issue]

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto

